name: weather_station_app
description: "A weather station mobile application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0" # Fixed SDK version format

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.8
  csv: ^6.0.0

  firebase_core: ^2.24.0
  firebase_auth: ^4.11.0
  google_sign_in: ^6.1.5  # if you want Google Sign-In
  flutter_signin_button: ^2.0.0  # for auth provider buttons

dev_dependencies: # Fixed indentation (no space before)
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Fixed indentation (2 spaces)

flutter:
  uses-material-design: true